#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : azure-common
Version  : 1.1.23
Release  : 11
URL      : https://files.pythonhosted.org/packages/e4/c9/0300b5a409a3758c0b6f77df5d8816366c9516579d065210ef3a2f21e23a/azure-common-1.1.23.zip
Source0  : https://files.pythonhosted.org/packages/e4/c9/0300b5a409a3758c0b6f77df5d8816366c9516579d065210ef3a2f21e23a/azure-common-1.1.23.zip
Summary  : Microsoft Azure Client Library for Python (Common)
Group    : Development/Tools
License  : MIT
Requires: azure-common-python = %{version}-%{release}
Requires: azure-common-python3 = %{version}-%{release}
Requires: azure-nspkg
BuildRequires : azure-nspkg
BuildRequires : buildreq-distutils3

%description
Microsoft Azure SDK for Python
==============================
This is the Microsoft Azure common code.

%package python
Summary: python components for the azure-common package.
Group: Default
Requires: azure-common-python3 = %{version}-%{release}

%description python
python components for the azure-common package.


%package python3
Summary: python3 components for the azure-common package.
Group: Default
Requires: python3-core

%description python3
python3 components for the azure-common package.


%prep
%setup -q -n azure-common-1.1.23

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1561437056
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
